# Generated by Django 3.1.4 on 2021-01-06 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='model_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='model_requests',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='model_states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='model_status',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='model_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_desc', models.TextField()),
                ('request_city', models.CharField(max_length=40, null=True)),
                ('request_pincode', models.IntegerField(null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_ccode', models.CharField(max_length=13, null=True)),
                ('request_number', models.CharField(max_length=13, null=True)),
                ('request_remark', models.TextField(null=True)),
                ('request_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.model_admin')),
                ('request_states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.model_states')),
                ('request_status', models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='Tickets.model_status')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.model_requests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
