# Generated by Django 4.0.4 on 2022-05-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_remark', models.TextField(null=True)),
                ('request_status', models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='Tickets.model_status')),
            ],
        ),
    ]
